# Kubernetes service configurations for load balancing and service discovery

# Ingress for external access
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: video-processing-ingress
  namespace: video-processing
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "2g"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  rules:
  - host: video-processing.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: video-processing-web-service
            port:
              number: 80
      - path: /flower
        pathType: Prefix
        backend:
          service:
            name: flower-service
            port:
              number: 5555
---
# Service for web application with load balancing
apiVersion: v1
kind: Service
metadata:
  name: video-processing-web-service
  namespace: video-processing
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    app: video-processing-web
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  type: LoadBalancer
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
---
# Service for Celery workers
apiVersion: v1
kind: Service
metadata:
  name: video-processing-worker-service
  namespace: video-processing
spec:
  selector:
    app: video-processing-worker
  ports:
  - name: metrics
    port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
---
# Service for Flower monitoring
apiVersion: v1
kind: Service
metadata:
  name: flower-service
  namespace: video-processing
spec:
  selector:
    app: flower
  ports:
  - name: http
    port: 5555
    targetPort: 5555
    protocol: TCP
  type: LoadBalancer
---
# Service for PostgreSQL
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: video-processing
spec:
  selector:
    app: postgres
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP
---
# Service for Redis
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: video-processing
spec:
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  type: ClusterIP
